### ISSUE TITLE
Reset has been renamed to logout in the upcoming 1.9.0 release

### ISSUE THREAD

**Issue by Mikescops** [BenjaminOddou/alfred-dashlane#3]
Just to make sure you don't miss it, in the upcoming release 1.9.0 `reset` is now `logout`. 

Ref: https://github.com/Dashlane/dashlane-cli/commit/96cb501b730b35a75526cd90efedc6db0f5b49e0

Your code:
https://github.com/BenjaminOddou/alfred-dashlane/blob/1422cc2907d834170c85d80d20956325fd4831df/src/reset.py#L13

**Comment by BenjaminOddou** [comment]
Nice ! I'll make the update for the next release 😄
